---
name: dxmm
version: 1

# APP CONFIG
APP_KEY: "2986120742"
APP_SECRET: "796b90d5a6e3a1cc4d719726f5f99f7d"
CALLBACK_URL: "http://dxmm.sinaapp.com/callback"

# FLASK CONFIG
DEBUG: 1
SECRET_KEY: "http://github.com/wangxiaomo"
...
